FROM nginx

MAINTAINER Gianpaolo Macario <gmacario@gmail.com>

# Setup Nginx Server Blocks
# See http://www.unixmen.com/setup-nginx-server-blocks-virtual-hosts-on-ubuntu-15-10/

RUN echo "<html><body><p>Welcome to gmoffice.solarma.it Website</p></body></html>" >/usr/share/nginx/html/index.html

# EOF
