maxlab-webproxy:
  build: maxlab-webproxy/
  ports:
    - 6080:80

web-test:
  build: web-test/
  ports:
    - "7080:80"

nginx-ssl-proxy:
  image: danieldent/nginx-ssl-proxy
  restart: always
  environment:
    UPSTREAM: cam01-internal.solarma.it:80
    #UPSTREAM: mv-linux-powerhorse.solarma.it:7080
    #UPSTREAM: mv-linux-powerhorse.solarma.it:9080
    #
    SERVERNAME: gmoffice.solarma.it
    #SERVERNAME: maxlab.polito.it
  ports:
    - "80:80"
    - "443:443"
#  links:
#    - web-test:appserver
  volumes:
    - "/certs"

# maxlab-polito-it:

# EOF
