# See also:
# - Compose file reference: https://docs.docker.com/compose/compose-file/

version: '2'

services:

  maxlab-polito-it:
    build: maxlab-polito-it/
    ports:
      - 6180:80
    environment:
      - VIRTUAL_HOST=maxlab.polito.it
      - LETSENCRYPT_HOST=maxlab.polito.it
      - LETSENCRYPT_EMAIL=webmaster@solarma.it
      - LETSENCRYPT_TEST=true

  gmoffice-solarma-it:
    build: gmoffice-solarma-it/
    ports:
      - 6280:80
    environment:
      - VIRTUAL_HOST=gmoffice.solarma.it
      - LETSENCRYPT_HOST=gmoffice.solarma.it
      - LETSENCRYPT_EMAIL=webmaster@solarma.it
      - LETSENCRYPT_TEST=true

  test2-solarma-it:
    image: jwilder/whoami
    ports:
      - 6380:8000
    environment:
      - VIRTUAL_HOST=test2.solarma.it
      - LETSENCRYPT_HOST=test2.solarma.it
      - LETSENCRYPT_EMAIL=webmaster@solarma.it
      - LETSENCRYPT_TEST=true

## www-solarma-it:
##   build: www-solarma-it/
##   ports:
##     - 6380:80

## maxlab-webproxy:
##   build: maxlab-webproxy/
##   ports:
##     - 6980:80

# web-test:
#   build: web-test/
#   ports:
#     - "7080:80"

  ## whoami:
  ##   image: jwilder/whoami
  ##   # container_name: whoami
  ##   ports:
  ##     - 8000:8000
  ##   environment:
  ##     - VIRTUAL_HOST=whoami.local

  nginx-proxy:
    image: jwilder/nginx-proxy
    # container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - proxy-certs:/etc/nginx/certs:rw
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx-proxy:rw

### nginx-ssl-proxy:
###   image: danieldent/nginx-ssl-proxy
###   restart: always
###   environment:
###     #UPSTREAM: dm-99-100.solarma.it:6980
###     UPSTREAM: cam01-internal.solarma.it:80
###     #UPSTREAM: mv-linux-powerhorse.solarma.it:7080
###     #UPSTREAM: mv-linux-powerhorse.solarma.it:9080
###     #
###     #SERVERNAME: dm-99-100.solarma.it
###     SERVERNAME: gmoffice.solarma.it
###     #SERVERNAME: maxlab.polito.it
###   ports:
###     - "80:80"
###     - "443:443"
### #  links:
### #    - web-test:appserver
###   volumes:
###     - "/certs"

  ## proxygen:
  ##   build: proxygen-templates/
  ##   container_name: 'proxygen'
  ##   volumes:
  ##       - '/var/run/docker.sock:/tmp/docker.sock:ro'
  ##       - proxy-conf:/conf
  ##   command: '-watch -notify-sighup=proxy /templates/proxy.tmpl /conf/proxy.conf'
  ##   tty: true
  ##   stdin_open: true
  ##   restart: always

  ## proxy:
  ##   image: 'nginx'
  ##   container_name: 'proxy'
  ##   volumes:
  ##       - proxy-conf:/etc/nginx/conf.d:ro
  ##       - proxy-certs:/etc/nginx/certs:ro
  ##   ports:
  ##       - '80:80'
  ##       - '443:443'
  ##   tty: true
  ##   stdin_open: true
  ##   restart: always

##   plain-nginx:
##     image: 'nginx'
##     container_name: 'plain-nginx'
##     # volumes:
##     #    - '/var/lib/docker/data/proxy/conf.d:/etc/nginx/conf.d:ro'
##     #    - '/var/lib/docker/data/proxy/certs:/etc/nginx/certs:ro'
##     ports:
##         - '8080:80'
##         # - '443:443'
##     tty: true
##     stdin_open: true
##     restart: always

# ---------------------

volumes:
    proxy-conf:
    proxy-certs:

# EOF
