FROM nginx

MAINTAINER Gianpaolo Macario <gmacario@gmail.com>

# Setup Nginx Server Blocks
# See http://www.unixmen.com/setup-nginx-server-blocks-virtual-hosts-on-ubuntu-15-10/

#RUN mkdir -p /var/www/html/unixmen1.local/public_html
#RUN echo "Welcome to unixmen1.local Website" >/var/www/html/unixmen1.local/public_html/index.html
#RUN chown -R www-data:www-data /var/www/html/unixmen1.local/public_html
#COPY unixmen1.conf /etc/nginx/conf.d/unixmen1.conf

#RUN mkdir -p /var/www/html/unixmen2.local/public_html
#RUN echo "Welcome to unixmen2.local Website" >/var/www/html/unixmen1.local/public_html/index.html
#RUN chown -R www-data:www-data /var/www/html/unixmen2.local/public_html
#COPY unixmen2.conf /etc/nginx/conf.d/unixmen2.conf

#RUN chmod -R 755 /var/www/html

#RUN echo "127.0.0.1 unixmen1.local" >>/etc/hosts
#RUN echo "127.0.0.1 unixmen2.local" >>/etc/hosts

# RUN cp /etc/nginx/nginx.conf
